### PR TITLE
optional range consolidation via save options

### LINKED ISSUE #989: XLConditionalFormat formats independent columns as one range for ColorScale
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.94

**What is the current behavior?**

When trying to format several independent columns using ColorScale, all of them are formating in one range.

**What is the expected behavior or new feature?**

Each column is formatting separately.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
    using (var output = new MemoryStream())
            {
                using (var wb = new XLWorkbook())
                {
                    var sheet = wb.Worksheets.Add("test");
                    sheet.Column(1).AddConditionalFormat().ColorScale()
                    .LowestValue(XLColor.FromHtml("#f56a6d"))
                    .Midpoint(XLCFContentType.Percent, 50, XLColor.FromHtml("#fdec84"))
                    .HighestValue(XLColor.FromHtml("#63be7b"));

                    sheet.Column(2).AddConditionalFormat().ColorScale()
                    .LowestValue(XLColor.FromHtml("#f56a6d"))
                    .Midpoint(XLCFContentType.Percent, 50, XLColor.FromHtml("#fdec84"))
                    .HighestValue(XLColor.FromHtml("#63be7b"));

                    wb.SaveAs(output);
                }
            }
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

Current result:
default

Expected result:

### LINKED ISSUE #1113: add Databars (conditional formatting) without format consolidation
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.94.2

**What is the current behavior?**

I want to add a databar as conditional formatting rules for several columns of a table. Unfortunately, the ranges for all columns are consolidated. Therefore the size of the databars are depicted based on the lowest/ highest value in all ranges together.

**What is the expected behavior or new feature?**

I want to add a databar for each column separately (as separate conditional formatting rule) resp. supress conditional formatting consolidation, so that the size of a data bar is calculated based on the lowest/ highest value in each column separately.

**Did this work in previous versions of our tool?  Which versions?**

No (not sure)

## Reproducibility

**Code to reproduce problem:**
```c#
 foreach (var column in listOfColumnNames)
            {             resultTable.DataRange.Column(column).AddConditionalFormat().DataBar(numberFormattingColor).LowestValue().HighestValue();
            }
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)
currentresult
expectedresult

### PR DESCRIPTION
**Pull request by ladida28**
#### What's this PR do?
this PR adds two more options to save_options
- Boolean ConsolidateConditionalFormatRanges
- Boolean ConsolidateDataValidationRanges

Therewith it can be configured, whether ranges are consolidated for conditional formats and data validation when the workbook is saved. Per default both are set to true

#### Where should the reviewer start?
two tests are added:
- OptionalRangeConsolidationWithoutConsolidation
- OptionalRangeConsolidationWithConsolidation

#### How should this be manually tested?
from my perspective, manual tests are not necessary, test are available

#### Any background context you want to provide?
Closes #1113 
Closes #989

#### Questions:
- Is there a blog post?
no
- Does the knowledge base need an update?
yes: the two options should be explained
- Does this add new (C#) dependencies?
no

- [ ] C# Code Review: @csreviewer
- [ ] Test Automation Review: @csreviewer

### CODE REVIEW

File: ClosedXML_Tests/Excel/ConditionalFormats/ConditionalFormatTests.cs [hunk 1]
```diff
@@ -21,5 +21,41 @@ public void MaintainConditionalFormattingOrder()
...
+            var options = new SaveOptions
+            {
+                ConsolidateConditionalFormatRanges = false,
+                ConsolidateDataValidationRanges = false
+            };
+
+            using (var stream = TestHelper.GetStreamFromResource(TestHelper.GetResourcePath(@"Other\StyleReferenceFiles\ConditionalFormattingOptional\inputfile_multiple_ranges.xlsx")))
+            using (var ms = new MemoryStream())
+            {
+                TestHelper.CreateAndCompare(() =>
```
Comment (Pankraty) [inline ClosedXML_Tests/Excel/ConditionalFormats/ConditionalFormatTests.cs]: These CreateAndCompare tests bring a lot of headaches because every time the saving logic changes many of such tests start to fail even if the changes have no relation to a feature under testing.

This is why I recommend avoiding such kinds of tests if possible and leave them for complicated cases only.

So, if you are intended to check that `ConsolidateConditionalFormatRanges = false` turns the consolidation off, then just save the file to a memory stream, load it from there and ensure a number of conditional formats is 2. Same for data validations. This way the test will be much easier to support.

File: ClosedXML/Excel/SaveOptions.cs [hunk 2]
```diff
@@ -17,5 +17,7 @@ public SaveOptions()
         public Boolean EvaluateFormulasBeforeSaving { get; set; } = false;
         public Boolean GenerateCalculationChain { get; set; } = true;
         public Boolean ValidatePackage { get; set; }
+        public Boolean ConsolidateConditionalFormatRanges { get; set; } = true;
+        public Boolean ConsolidateDataValidationRanges { get; set; } = true;
```
Comment (Pankraty) [inline ClosedXML/Excel/SaveOptions.cs]: I believe the properties are ordered alphabetically. Put these two accordingly.

File: ClosedXML/Excel/XLWorkbook_Save.cs [hunk 3]
```diff
@@ -304,7 +304,7 @@ private void CreateParts(SpreadsheetDocument document, SaveOptions options)
                     GenerateVmlDrawingPartContent(vmlDrawingPart, worksheet, context);
                 }
 
-                GenerateWorksheetPartContent(worksheetPart, worksheet, options.EvaluateFormulasBeforeSaving, context);
+                GenerateWorksheetPartContent(worksheetPart, worksheet, options.EvaluateFormulasBeforeSaving, options.ConsolidateConditionalFormatRanges, options.ConsolidateDataValidationRanges, context);
```
Comment (Pankraty) [inline ClosedXML/Excel/XLWorkbook_Save.cs]: Maybe simply pass `SaveOptions` to the method? For one flag it was OK to pass a boolean, but for three it looks weird.

File: ClosedXML_Tests/TestHelper.cs [hunk 4]
```diff
@@ -101,7 +101,7 @@ public static void RunTestExample<T>(string filePartName, bool evaluateFormulae
             }
         }
 
-        public static void CreateAndCompare(Func<IXLWorkbook> workbookGenerator, string referenceResource, bool evaluateFormulae = false)
+        public static void CreateAndCompare(Func<IXLWorkbook> workbookGenerator, string referenceResource, bool evaluateFormulae = false, SaveOptions options = null)
```
Comment (Pankraty) [inline ClosedXML_Tests/TestHelper.cs]: Once `options` has been added there is no sense in `evaluateFormulae` argument. Remove it.

Comment (Pankraty) [reply ClosedXML_Tests/TestHelper.cs]: On the other hand, if you get rid of CreateAndCompare tests you added, this method may be reverted.

File: ClosedXML/Excel/XLWorkbook_Save.cs [hunk 5]
```diff
@@ -4473,9 +4473,13 @@ private static bool NumberFormatsAreEqual(NumberingFormat nf, XLNumberFormatValu
         #region GenerateWorksheetPartContent
 
         private static void GenerateWorksheetPartContent(
-            WorksheetPart worksheetPart, XLWorksheet xlWorksheet, bool evaluateFormulae, SaveContext context)
+            WorksheetPart worksheetPart, XLWorksheet xlWorksheet, bool evaluateFormulae, bool consolidateConditionalFormatRanges, bool consolidateDataValidationRanges, SaveContext context)
         {
-            ((XLConditionalFormats)xlWorksheet.ConditionalFormats).Consolidate();
+            if(consolidateConditionalFormatRanges)
```
Comment (Pankraty) [inline ClosedXML/Excel/XLWorkbook_Save.cs]: Add a space after `if`

File: ClosedXML/Excel/XLWorkbook_Save.cs [hunk 6]
```diff
@@ -5359,7 +5363,12 @@ private static bool NumberFormatsAreEqual(NumberingFormat nf, XLNumberFormatValu
                 var dataValidations = worksheetPart.Worksheet.Elements<DataValidations>().First();
                 cm.SetElement(XLWorksheetContents.DataValidations, dataValidations);
                 dataValidations.RemoveAllChildren<DataValidation>();
-                xlWorksheet.DataValidations.Consolidate();
+
+                if(consolidateDataValidationRanges)
```
Comment (Pankraty) [inline ClosedXML/Excel/XLWorkbook_Save.cs]: Add a space after `if`

File: ClosedXML/Excel/XLWorkbook_Save.cs (hunk 5 above)
Comment (igitur) [reply ClosedXML/Excel/XLWorkbook_Save.cs]: To add to this, install the CodeMaid Visual Studio plugin and do a CodeMaid Clean on each file that you have altered. It will ensure the whitespace is in line with our convention.

**Comment by Pankraty** [comment]
Besides making a consolidation optional (which may benefit performance), I would fix the `XLConditionalFormats.Consolidate` method in order to exclude certain types of conditional formats (i.e. `ColorScale`, `DataBar`, something else?) from a consolidation. They must not be screwed up even if the user enforces a consolidation.

The fix should be trivial, I expect, but it will require adding a couple more tests.

**Comment by igitur** [comment]
@ladida28 FYI, I just added some developer guidelines. Hopefully this helps. https://github.com/ClosedXML/ClosedXML/blob/develop/CONTRIBUTING.md

File: ClosedXML_Tests/Excel/ConditionalFormats/ConditionalFormatTests.cs (hunk 1 above)
Comment (ladida28) [reply ClosedXML_Tests/Excel/ConditionalFormats/ConditionalFormatTests.cs]: test implementation updated

File: ClosedXML/Excel/SaveOptions.cs (hunk 2 above)
Comment (ladida28) [reply ClosedXML/Excel/SaveOptions.cs]: codemaid applied in new version

File: ClosedXML/Excel/XLWorkbook_Save.cs (hunk 3 above)
Comment (ladida28) [reply ClosedXML/Excel/XLWorkbook_Save.cs]: adjusted according to your comment

File: ClosedXML_Tests/TestHelper.cs (hunk 4 above)
Comment (ladida28) [reply ClosedXML_Tests/TestHelper.cs]: test implementation adjusted - no createAndCompare used anymore

File: ClosedXML/Excel/XLWorkbook_Save.cs (hunk 5 above)
Comment (ladida28) [reply ClosedXML/Excel/XLWorkbook_Save.cs]: codemaid applied

File: ClosedXML/Excel/XLWorkbook_Save.cs (hunk 6 above)
Comment (ladida28) [reply ClosedXML/Excel/XLWorkbook_Save.cs]: codemaid applied

**Comment by ladida28** [comment]
I can implement this, but I am not sure were to store the list of conditionalFormatTypes, that should be excluded.
Option 1: directly in XLConditionalFormats
Option 2: configurable via save_options
Option 3: somewhere else?

What would you suggest?

> Besides making a consolidation optional (which may benefit performance), I would fix the `XLConditionalFormats.Consolidate` method in order to exclude certain types of conditional formats (i.e. `ColorScale`, `DataBar`, something else?) from a consolidation. They must not be screwed up even if the user enforces a consolidation.
> 
> The fix should be trivial, I expect, but it will require adding a couple more tests.

**Comment by Pankraty** [comment]
>Option 1: directly in XLConditionalFormats
>Option 2: configurable via save_options
>Option 3: somewhere else?

It's definitely not a save option, such formats should be excluded from a consolidation at all. So I suggest putting an additional check right in XLConditionalFormats.Consolidate().

File: ClosedXML_Tests/Excel/ConditionalFormats/ConditionalFormatTests.cs [hunk 7]
```diff
@@ -21,5 +22,51 @@ public void MaintainConditionalFormattingOrder()
...
         }
+
+        [Test]
+        public void OptionalRangeConsolidationWithoutConsolidation()
+        {
+            var options = new SaveOptions
+            {
+                ConsolidateConditionalFormatRanges = false,
+                ConsolidateDataValidationRanges = false
+            };
```
Comment (Pankraty) [inline ClosedXML_Tests/Excel/ConditionalFormats/ConditionalFormatTests.cs]: Now it is much better. But still, this test checks too many things at once. 

So,
1. Join `OptionalRangeConsolidationWithoutConsolidation` and `OptionalRangeConsolidationWithConsolidation` in one test `ConsolidationDoesNotAffectDataBarAndColorScale`. There you don't even have to save a workbook. You can call `((XLConditionalFormats)(ws.ConditionalFormats)).Consolidate()` directly.
2. Add another test to check that `ConsolidateConditionalFormatRanges` has the effect. For this, you will create some "ordinary" conditional formats that are supposed to be consolidated with the option turned on. To avoid code duplication, create a single test with two test cases (e.g. 
```
[TestCase(true, 1)]
[TestCase(false, 2)]
public void SaveOptionAffectsConsolidation(bool consolidateConditionalFormatRanges, int expectedCount)
```
3. In `DataValidationTests` create a similar test with two test cases for conditional formats consolidation.

Comment (Pankraty) [reply ClosedXML_Tests/Excel/ConditionalFormats/ConditionalFormatTests.cs]: Besides, once you removed those CreateAndCompare tests you also have to remove XLSX files (ConditionalFormattingOptional_consolidated.xlsx, ConditionalFormattingOptional_not_consolidated.xlsx, 
inputfile_multiple_ranges.xlsx)

Comment (ladida28) [reply ClosedXML_Tests/Excel/ConditionalFormats/ConditionalFormatTests.cs]: files removed

Comment (ladida28) [reply ClosedXML_Tests/Excel/ConditionalFormats/ConditionalFormatTests.cs]: test case implementation adjusted

**Comment by ladida28** [comment]
> > Option 1: directly in XLConditionalFormats
> > Option 2: configurable via save_options
> > Option 3: somewhere else?
> 
> It's definitely not a save option, such formats should be excluded from a consolidation at all. So I suggest putting an additional check right in XLConditionalFormats.Consolidate().

I adjusted XLConditionalFormats.Consolidate() according to your comments

**Comment by Pankraty** [comment]
Good work! Thanks for the contribution and do not stop ;) There is a whole lot of tasks to address.

**Comment by ladida28** [comment]
> Good work! Thanks for the contribution and do not stop ;) There is a whole lot of tasks to address.

Thanks. Do you already know when it will be merged? Will it be part of v0.95. I am desperately waiting for this change :)

Besides, I am thinking about adding support for data slicers, but I actually do not really know, where to start. Any recommendations are welcome

**Comment by Pankraty** [comment]
> Thanks. Do you already know when it will be merged? Will it be part of v0.95. I am desperately waiting for this change :)

This is up to @igitur to decide.

> Besides, I am thinking about adding support for data slicers, but I actually do not really know, where to start. Any recommendations are welcome

I would start from opening a new issue since it has no relation to this PR :)

File: ClosedXML/Excel/ConditionalFormats/XLConditionalFormats.cs [hunk 8]
```diff
@@ -1,13 +1,24 @@
...
 using System.Linq;
-using System.Text;
 
 namespace ClosedXML.Excel
 {
     internal class XLConditionalFormats : IXLConditionalFormats
     {
         private readonly List<IXLConditionalFormat> _conditionalFormats = new List<IXLConditionalFormat>();
+
+        private readonly List<XLConditionalFormatType> _conditionalFormatTypesExcludedFromConsolidation = new List<XLConditionalFormatType>()
```
Comment (igitur) [inline ClosedXML/Excel/ConditionalFormats/XLConditionalFormats.cs]: This could be `static`. Maybe better to use `HashSet<>`, @Pankraty ?

Comment (igitur) [reply ClosedXML/Excel/ConditionalFormats/XLConditionalFormats.cs]: @ladida28 Please make this static.

**Comment by igitur** [comment]
@ladida28 Are you comfortable with rewriting git history? Ideally I want to squash this into 2 commits. I'll give more info later, if you can rewrite git history.

**Comment by ladida28** [comment]
> @ladida28 Are you comfortable with rewriting git history? Ideally I want to squash this into 2 commits. I'll give more info later, if you can rewrite git history.

@igitur Never did that before but I can give it a try using smartgit. Which commits should be squashed together?

**Comment by igitur** [comment]
Ok, nevermind, it's OK to leave it as is. I'll squash it all into 1 commit. Just see the last review comment, please.

File: ClosedXML/Excel/ConditionalFormats/XLConditionalFormats.cs (hunk 8 above)
Comment (ladida28) [reply ClosedXML/Excel/ConditionalFormats/XLConditionalFormats.cs]: static is set

**Comment by ladida28** [comment]
> > Thanks. Do you already know when it will be merged? Will it be part of v0.95. I am desperately waiting for this change :)
> 
> This is up to @igitur to decide.
> 
> > Besides, I am thinking about adding support for data slicers, but I actually do not really know, where to start. Any recommendations are welcome
> 
> I would start from opening a new issue since it has no relation to this PR :)

comming soon :)

**Comment by igitur** [comment]
Thanks for the contribution
