### PR TITLE
Fix. Failed to "SaveAs" a file with a ReadOnly attribute

### LINKED ISSUE #640: Failed to "SaveAs" a file with a ReadOnly attribute
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.90.0

**What is the current behavior?**

If open a file having a read-only attribute and then try to save it as a copy (with a different name) the operation fails (UserNotAuthorizedException). The copy of the original file is created though.

**What is the expected behavior or new feature?**

The file must be successfully saved at the specified location. It must have no ReadOnly attribute.

**Did this work in previous versions of our tool?  Which versions?**

No (as far as I am aware of)

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

A pull request with a test case will be provided soon.

**Code to reproduce problem:**
```c#
public void Main()
{
            string id = Guid.NewGuid().ToString();
            string original = string.Format("{0}original{1}.xlsx", _tempFolder, id);
            string copy = string.Format("{0}copy_of_{1}.xlsx", _tempFolder, id);

            using (var wb = new XLWorkbook())
            {
                var sheet = wb.Worksheets.Add("TestSheet");
                wb.SaveAs(original);
            }
            System.IO.File.SetAttributes(original, FileAttributes.ReadOnly);

            using (var wb = new XLWorkbook(original))
            {
                wb.SaveAs(copy); // This step fails
            }
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

### PR DESCRIPTION
**Pull request by Pankraty**
#### Fixes #640
- [ ] C# Code Review: @csreviewer
- [ ] Test Automation Review: @csreviewer

### CODE REVIEW

**Comment by igitur** [comment]
In the case that the file does already exist and be read only, I don't think we should clear the flag.

**Comment by vbjay** [comment]
Exactly why I asked what I asked in the issue. He did say the file to be
written does not exist.

**Comment by igitur** [comment]
In his specific case the file doesn't already exist, but if you look at the patch he submitted, it doesn't make an provision for when the file does exist. And it should.

**Comment by Pankraty** [comment]
>  it doesn't make an provision for when the file does exist. And it should.
With the provided fix, method SaveAs fails on overwriting an existing file with a ReadOnly flag, and silently overwrites one without this flag (since "overwrite" parameter was specified in File.Copy method). 
Does not it seem like an expected behavior?

**Comment by igitur** [comment]
Ah OK, that sounds good then.

**Comment by Pankraty** [comment]
Added couple more tests for these cases.

File: ClosedXML/Excel/XLWorkbook.cs [hunk 1]
```diff
@@ -498,7 +498,10 @@ public void SaveAs(String file, SaveOptions options)
             else if (_loadSource == XLLoadSource.File)
             {
                 if (String.Compare(_originalFile.Trim(), file.Trim(), true) != 0)
+                {
                     File.Copy(_originalFile, file, true);
+                    File.SetAttributes(file, FileAttributes.Normal);
```
Comment (igitur) [inline ClosedXML/Excel/XLWorkbook.cs]: And if `_loadSource` is something else? I think the `File.SetAttributes` should be lower down, outside the `if` statements.

Comment (igitur) [reply ClosedXML/Excel/XLWorkbook.cs]: I'm wrong. It's not needed for the other `_loadSource` values. I do, however, think we need to catch that specific exception and rethrow it with a more meaningful message. What do you think?

Comment (Pankraty) [reply ClosedXML/Excel/XLWorkbook.cs]: That sounds reasonable. On the other hand, File.Copy may fail due to plenty of reasons (invalid path, network failure, disk is full, user has no permissions, file is busy, etc.). Each of them would cause a different exception, more or less specific.
Does this make sense to process some of these cases (like overwriting a read-only file) separately, making the exception more specific than is thrown by the framework? Probably, yes, assuming than user would expect some kind of IO.Exception to be thrown on saving failure, but I am not sure.

**Comment by vbjay** [comment]
I don't see a problem of using InnerException. Throw an exception that
contains the original exception.

**Comment by igitur** [comment]
Merged. We can deal with the exceptions later. Need to think about it, list what we can and decide which we're going to catch.

Thanks for the contribution.

File: ClosedXML_Tests/Excel/Saving/SavingTests.cs [hunk 2]
```diff
@@ -1,15 +1,28 @@
...
 namespace ClosedXML_Tests.Excel.Saving
 {
     [TestFixture]
     public class SavingTests
     {
+        private string _tempFolder;
+        private List<string> _tempFiles;
+
+        [SetUp]
+        public void Setup()
```
Comment (igitur) [inline ClosedXML_Tests/Excel/Saving/SavingTests.cs]: I missed this. Can you check whether you can rather use the `using (var tf = new TemporaryFile(...))` pattern as in `OleDbTests`. Using that pattern would clean up any test files automatically.
