### PR TITLE
Treat missing numberFormatId as General numberformat

### LINKED ISSUE #1275: Exception with empty numFmts and no NumberFormatId
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**
0.94.2

**What is the current behavior?**
A minimal xlsx with an empty numFmts `<x:numFmts count="0" />`
and no NumberFormatId attribute in CellFormats `<x:cellStyleXfs count="2"> <x:xf fontId="0" />`
will throw an exception while loading.

Exception:
`xlCell.InnerStyle.NumberFormat.NumberFormatId = Int32.Parse(numberFormatId);`
```
Value cannot be null.
Parameter name: String
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at ClosedXML.Excel.XLWorkbook.LoadCells(SharedStringItem[] sharedStrings, Stylesheet s, NumberingFormats numberingFormats, Fills fills, Borders borders, Fonts fonts, Dictionary 2 sharedFormulasR1C1, XLWorksheet ws, Dictionary 2 styleList, Cell cell, Int32 rowIndex)
```

**What is the expected behavior or new feature?**
File should load without error.
Excel or LibreOffice will open the file.

**Did this work in previous versions of our tool?  Which versions?**
Unknown

## Reproducibility
**Code to reproduce problem:**
```c#
public void Main()
{
  var workbook = new XLWorkbook("empty-numFmts.xlsx");
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[empty-numFmts.xlsx](https://github.com/ClosedXML/ClosedXML/files/3526839/empty-numFmts.xlsx)

### PR DESCRIPTION
**Pull request by igitur**
Fixes #1275

### CODE REVIEW

File: ClosedXML/Excel/XLWorkbook_Load.cs [hunk 1]
```diff
@@ -1816,21 +1816,27 @@ private static void ParseReference(string item, out string sheetName, out string
...
+                            s.NumberingFormats.Any(nf => ((NumberingFormat)nf).NumberFormatId.Value == numberFormatId))
+                        {
+                            xlCell.InnerStyle.NumberFormat.Format =
+                                ((NumberingFormat)s.NumberingFormats
+                                                    .First(
+                                                        nf => ((NumberingFormat)nf).NumberFormatId.Value == numberFormatId)
+                                ).FormatCode.Value;
+                        }
+                        else
+                            xlCell.InnerStyle.NumberFormat.NumberFormatId = Int32.Parse(numberFormatId);
```
Comment (Pankraty) [inline ClosedXML/Excel/XLWorkbook_Load.cs]: Does not it look bulky?
What if replace the block inside `if()` with
```
var format = s.NumberingFormats?
    .Cast<NumberingFormat>()
    .Where(nf => nf.NumberFormatId.Value == numberFormatId)
    .Select(nf => nf.FormatCode.Value)
    .FirstOrDefault();

if (format == null)
    xlCell.InnerStyle.NumberFormat.NumberFormatId = Int32.Parse(numberFormatId);
else
    xlCell.InnerStyle.NumberFormat.Format = format;
```
This way we avoid double enumeration of the collection (`.Any()` and then `.First()`).

Comment (igitur) [reply ClosedXML/Excel/XLWorkbook_Load.cs]: done
