### PR TITLE
Fixed file is used in another process error

### LINKED ISSUE #1557: Using ClosedXML.Excel.Drawings.XLPictures.Add(string imageFile) sometimes throwing file lock error
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95.3

**What is the current behavior?**

With many concurrent requests, we are getting following error in adding image in excel - "The process cannot access the file <FileName> because it is being used by another process"

**What is the expected behavior or new feature?**

There should not be error since file is accessed for only reading. This can be easily achieved by opening image file in mode read and share read done by File.OpenRead method.

**Is this a regression from the previous version?**
No

## Reproducibility
NA - Error may come up with large number of requests.

### PR DESCRIPTION
**Pull request by ChiragRupani**
Resolves #1557

### CODE REVIEW

**Review by Pankraty — COMMENTED** [review]
The fix looks good but could you also add a test for this? It does not even need to involve concurrency: just open a file for reading and, while it's open, try to insert the same file as a picture to xlsx.

File: ClosedXML/Excel/Drawings/XLPictures.cs [hunk 1]
```diff
@@ -74,7 +74,7 @@ public IXLPicture Add(Bitmap bitmap, string name)
 
         public IXLPicture Add(string imageFile)
         {
-            using (var fs = File.Open(imageFile, FileMode.Open))
+            using (var fs = File.OpenRead(imageFile))
```
Comment (igitur) [inline ClosedXML/Excel/Drawings/XLPictures.cs:77]: I thought `File.Open(imageFile, FileMode.Open)` and `File.OpenRead(imageFile)` were equivalent. What's the diffierence?

Comment (Pankraty) [reply ClosedXML/Excel/Drawings/XLPictures.cs:77]: image

Comment (ChiragRupani) [reply ClosedXML/Excel/Drawings/XLPictures.cs:77]: Adding to it, Default [open ](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.open?view=net-5.0)- opens `FileStream` on specified path with read/write access with no sharing. I am seeing failures in our Asp.Net Core app because of that.

**Comment by ChiragRupani** [comment]
> 
> 
> The fix looks good but could you also add a test for this? It does not even need to involve concurrency: just open a file for reading and, while it's open, try to insert the same file as a picture to xlsx.

Opening file may not test correctly since we need to open with Read Mode and Read Sharing. Instead I added parallel invoke for adding same twice in excel, here I am able to reproduce the issue with existing code and passing with the fix.

**Review by igitur — APPROVED** [review]

**Comment by igitur** [comment]
Thanks for the fix.

**Comment by igitur** [comment]
After merging this, tests are failing on AppVeyor. Please check it out and try to fix the error. https://ci.appveyor.com/project/ClosedXML/closedxml/builds/36271811/job/lfrcgiapraffisll

**Comment by ChiragRupani** [comment]
I checked it - it happening due to adding new cell in excel workbook is not [thread safe](https://github.com/ClosedXML/ClosedXML/blob/7f077373f6e1aada0a8728126505ed07b7fd6766/ClosedXML/Excel/Cells/XLCellsCollection.cs#L54). The fix is to create and use workbook separately for each thread.

PR: #1562
