### PR TITLE
Workaround when parsing html color string fails

### LINKED ISSUE #675: Exception when creating new XLWorkbook object with list separator set to # in regional settings.
https://github.com/ClosedXML/ClosedXML/blob/31206f0258391561bfc5fc1f89819b01339dfdcb/ClosedXML/Excel/Style/Colors/XLColor_Static.cs#L49

## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**

0.91

**What is the current behavior?**

I use ClosedXML on machine where all Windows accounts are set with Croatian regional setting, and list separator set to # instead ; 

screenshot_20180131_100101

Exceptions is thrown when creating new XLWorkbook object in file ClosedXML/Excel/Style/Colors/XLColor_Static.cs on line 49.

Exception and Stack trace:

System.Exception occurred
  HResult=0x80131500
  Message= is not a valid value for Int32.
  Source=System

StackTrace:
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Drawing.ColorConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Drawing.ColorTranslator.FromHtml(String htmlColor)
   at ClosedXML.Excel.XLColor.FromHtml(String htmlColor) in ...\ClosedXML\Excel\Style\Colors\XLColor_Static.cs:line 49
   at ClosedXML.Excel.XLWorkbook.InitializeTheme() in ...\ClosedXML\Excel\XLWorkbook.cs:line 325
   at ClosedXML.Excel.XLWorkbook..ctor(XLEventTracking eventTracking) in ...\ClosedXML\Excel\XLWorkbook.cs:line 744
   at ClosedXML.Excel.XLWorkbook..ctor(String file, XLEventTracking eventTracking) in ...\ClosedXML\Excel\XLWorkbook.cs:line 770
   at ClosedXML.Excel.XLWorkbook..ctor(String file) in ...\ClosedXML\Excel\XLWorkbook.cs:line 765

**What is the expected behavior or new feature?**

No exception thrown. Workaround is to create new CultureInfo object and set list separator to ; then use this culture in program.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Bug is reproducible when creating new XLWorkbook object with above Regional settings.

**Code to reproduce problem:**
```VB

Dim workBook As XLWorkbook = New XLWorkbook()

### PR DESCRIPTION
**Pull request by igitur**
Fixes #675

### CODE REVIEW

File: ClosedXML/Utils/ColorStringParser.cs [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+        {
+            try
+            {
+                return ColorTranslator.FromHtml(htmlColor);
+            }
+            catch
+            {
+                // https://github.com/ClosedXML/ClosedXML/issues/675
+                // When regional settings list separator is # , the standard ColorTranslator.FromHtml fails
+                return Color.FromArgb(int.Parse(htmlColor.Replace("#", ""), NumberStyles.AllowHexSpecifier));
```
Comment (Pankraty) [inline ClosedXML/Utils/ColorStringParser.cs]: This would give a wrong result with FF00FF (Alpha will be 0 instead of 255, that is used by ColorTranslator by default)  or with FFF (in HTML it is equal to FFFFFFFF). I doubt this will be an issue in ClosedXML since it gets values stored in a file. Just FYI.

Comment (igitur) [reply ClosedXML/Utils/ColorStringParser.cs]: Yeah, you're right, but I'm not going to spend too much time on such an edge case. Merging this as is.
