### PR TITLE
IEnumerator improvements - avoid evaluation of empty sheets

### LINKED ISSUE #1390: NullReferenceException in CellRangeReference.GetEnumerator()
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.95

**What is the current behavior?**

Calling Workbook.SaveTo(Stream) results in the exception mentioned above. The call to

Range.Worksheet.LastCellUsed()

in 

CellRangeReference.GetEnumerator() 

returns null.

**Did this work in previous versions of our tool?  Which versions?**

Yes / v0.94

## Reproducibility
 
Unfortunately I cannot provide the workbook that causes this issue. If necessary I can try to reproduce the behaviour with a file I can share. This might be difficult as the workbook is quite complex, so I would need some directions as to what might be the cause of this. The full callstack is attached.

[callstack.txt](https://github.com/ClosedXML/ClosedXML/files/4437882/callstack.txt)

### PR DESCRIPTION
**Pull request by igitur**
Fixes #1390

### CODE REVIEW

File: ClosedXML/Excel/CalcEngine/Expression.cs [hunk 1]
```diff
@@ -509,10 +509,14 @@ public override object Evaluate()
...
-                return new[] { (string)_value }.GetEnumerator();
+            if (_value is string s)
+                yield return s;
 
-            return (_value as IEnumerable).GetEnumerator();
+            if (_value is IEnumerable ie)
+            {
+                foreach (var o in ie)
+                    yield return o;
+            }
```
Comment (igitur) [inline ClosedXML/Excel/CalcEngine/Expression.cs:519]: Maybe if `_value` is not `string` or `IEnumerable`, then we should just `yield return _value`?

File: ClosedXML/Excel/CalcEngine/Expression.cs [hunk 2]
```diff
@@ -509,10 +509,14 @@ public override object Evaluate()
 
         public IEnumerator GetEnumerator()
         {
-            if (_value is string)
-                return new[] { (string)_value }.GetEnumerator();
+            if (_value is string s)
+                yield return s;
 
-            return (_value as IEnumerable).GetEnumerator();
+            if (_value is IEnumerable ie)
```
Comment (Pankraty) [inline ClosedXML/Excel/CalcEngine/Expression.cs:515]: Here we should use `else if`, otherwise we'll return a string and _then_ all chars it consists of. A known gotcha of `yield return` ;)

File: ClosedXML/Excel/CalcEngine/Expression.cs (hunk 1 above)
Comment (Pankraty) [reply ClosedXML/Excel/CalcEngine/Expression.cs:519]: Yes, it makes sense.

**Comment by igitur** [comment]
@Pankraty I pushed new changed since you approved. Please just double-check that you still approve.

**Comment by Pankraty** [comment]
Looks good
