### PR TITLE
Fix issues with data validation rules

### LINKED ISSUE #680: Inserting rows above/below rows with range formatting and data validation causes Closed XML to hang
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.91.0

**What is the current behavior?**

Execution does not complete.  It will hang on the InsertRowsAbove(1) call near the end.

**What is the expected behavior or new feature?**

Execution should complete.  Closed XML should not hang.  This code should produce a simple Excel file.

**Did this work in previous versions of our tool?  Which versions?**

No.  We have tried several versions and have been able to consistently reproduce this issue.  This can be replicated in 0.87.1 very easily - you just need to change XLDataType enum references to XLCellValues.

## Reproducibility

**Code to reproduce problem:**
```c#
private const string OUTPUT_FILE = "c:\\temp\\test_output.xlsx";

static void Main(string[] args)
{
  //If output file already exists, nuke it
  if (System.IO.File.Exists(OUTPUT_FILE))
  {
    System.IO.File.Delete(OUTPUT_FILE);
  }

  //Prep book and sheets
  var workbook = new ClosedXML.Excel.XLWorkbook();
  var dataWorksheet = workbook.AddWorksheet("Data");
  var listWorksheet = workbook.AddWorksheet("Lists");

  //Setup List Sheet
  listWorksheet.Cell(1, 1).Value = "List";
  for (var rowptr = 2; rowptr <= 101; rowptr++)
  {
    listWorksheet.Cell(rowptr, 1).Value = (rowptr - 1).ToString();
    listWorksheet.Cell(rowptr, 1).SetValue<string>((rowptr - 1).ToString());
    listWorksheet.Cell(rowptr, 1).DataType = ClosedXML.Excel.XLDataType.Text;
  }

  //Setup Data Validation (comment last two lines to prevent breakage)
  var listRange = listWorksheet.Range(2, 1, 101, 1);
  var ddValidation = dataWorksheet.Range(2, 1, 9999, 1).SetDataValidation();
  ddValidation.List(listRange, true);
  ddValidation.AllowedValues = ClosedXML.Excel.XLAllowedValues.List;

  //Setup Data Sheet (comment last line to prevent breakage)
  dataWorksheet.Cell(1, 1).Value = "Data";
  dataWorksheet.Range(2, 1, 9999, 1).DataType = ClosedXML.Excel.XLDataType.Text;

  //Add Data to be Validated
  var rnd = new Random();
  for (var rowptr = 2; rowptr <= 11; rowptr++)
  {
    dataWorksheet.Cell(rowptr, 1).SetValue<string>(rnd.Next(1, 100).ToString());
  }

  //Insert a row (comment this line to prevent breakage)
  dataWorksheet.Row(2).InsertRowsAbove(1);

  //Save it
  workbook.SaveAs(OUTPUT_FILE);
}
```

### PR DESCRIPTION
**Pull request by Pankraty**
This PR fixes #680.

Accessing DataValidation property of either cell or range caused new data validation rules creation. If the cell was already included in some large data validation rule that rule was split into pieces - one data validation rule for each cell. If the original range included thousands of cells this could be catastrophic.

This PR removes an implicit creation of data validation rules from getters, so to create a new validation rule ```SetDataValidation``` method should be called explicitly. 

Two tests were muted until #686 is fixed.

- [ ] C# Code Review: @csreviewer
- [ ] Test Automation Review: @csreviewer

### CODE REVIEW

File: ClosedXML/Excel/Cells/XLCell.cs [hunk 1]
```diff
@@ -1309,18 +1301,17 @@ public IXLCell SetFormulaR1C1(String formula)
...
-                    {
-                        using (var rngs = dv.Ranges) return dv.IsDirty() && rngs.Contains(asRange);
-                    });
-            }
+            get { return DataValidation != null; }
         }
 
         public IXLDataValidation SetDataValidation()
         {
+            if (DataValidation != null)
```
Comment (igitur) [inline ClosedXML/Excel/Cells/XLCell.cs]: Simpler: (?)

```c#
if (DataValidation == null)
{
    using (var range = this.AsRange())
        Worksheet.DataValidations.Add(new XLDataValidation(range));
}
return DataValidation;
```

File: ClosedXML/Excel/DataValidation/XLDataValidation.cs [hunk 2]
```diff
@@ -1,23 +1,32 @@
 using System;
+using System.ComponentModel;
+using System.Linq;
 
 namespace ClosedXML.Excel
 {
     internal class XLDataValidation : IXLDataValidation
     {
-        public XLDataValidation(IXLRanges ranges)
+        public XLDataValidation()
```
Comment (igitur) [inline ClosedXML/Excel/DataValidation/XLDataValidation.cs]: Make this constructor `private`.

File: ClosedXML/Excel/DataValidation/XLDataValidation.cs [hunk 3]
```diff
@@ -1,23 +1,32 @@
...
-                               {
-                                   var newR =
-                                       new XLRange(new XLRangeParameters(r.RangeAddress as XLRangeAddress,
-                                                                         r.Worksheet.Style) {IgnoreEvents = true});
-                                   (Ranges as XLRanges).Add(newR);
-                               } );
             Initialize();
         }
 
+        public XLDataValidation(IXLRange range)
```
Comment (igitur) [inline ClosedXML/Excel/DataValidation/XLDataValidation.cs]: I swear I did the same change in some other PR, but I can't find it now. Weird.

File: ClosedXML_Tests/Excel/DataValidations/DataValidationTests.cs [hunk 4]
```diff
@@ -27,11 +27,11 @@ public void Validation_1()
 
             ws.Cell("A1").SetValue("Cell below has Validation Only.");
             cell = ws.Cell("A2");
-            cell.DataValidation.List(ws.Range("$E$1:$E$4"));
+            cell.SetDataValidation().List(ws.Range("$E$1:$E$4"));
```
Comment (igitur) [inline ClosedXML_Tests/Excel/DataValidations/DataValidationTests.cs]: Why did you change `.DataValidation.` to `.SetDataValidation().` in the tests?

**Comment by Pankraty** [comment]
Otherwise there would be NullReferenceException. I should have mentioned that this PR contains breaking changes.

File: ClosedXML_Tests/Excel/DataValidations/DataValidationTests.cs (hunk 4 above)
Comment (igitur) [reply ClosedXML_Tests/Excel/DataValidations/DataValidationTests.cs]: Is there no way to avoid this breaking change? This breaking change is very subtle and will confuse a lot of users. Please reply here in this thread, not the main thread.

Comment (Pankraty) [reply ClosedXML_Tests/Excel/DataValidations/DataValidationTests.cs]: >Otherwise there would be NullReferenceException. I should have mentioned that this PR contains breaking changes

You're right, better to avoid breaking changes. Will change

File: ClosedXML/Excel/XLWorkbook_Load.cs [hunk 5]
```diff
@@ -2090,8 +2090,9 @@ private static void LoadDataValidations(DataValidations dataValidations, XLWorks
             {
                 String txt = dvs.SequenceOfReferences.InnerText;
                 if (String.IsNullOrWhiteSpace(txt)) continue;
-                foreach (var dvt in txt.Split(' ').Select(rangeAddress => ws.Range(rangeAddress).DataValidation))
+                foreach (var range in txt.Split(' ').Select(rangeAddress => ws.Range(rangeAddress)))
```
Comment (igitur) [inline ClosedXML/Excel/XLWorkbook_Load.cs]: Not your fault, but I think we should dispose the range properly here to avoid unnecessary attached events.
```c#
                foreach (var rangeAddress in txt.Split(' '))
                {
                    using (var range = ws.Range(rangeAddress))
                    {
                        var dvt = range.SetDataValidation();
                        if (dvs.AllowBlank != null) dvt.IgnoreBlanks = dvs.AllowBlank;
                        if (dvs.ShowDropDown != null) dvt.InCellDropdown = !dvs.ShowDropDown.Value;
                        if (dvs.ShowErrorMessage != null) dvt.ShowErrorMessage = dvs.ShowErrorMessage;
                        if (dvs.ShowInputMessage != null) dvt.ShowInputMessage = dvs.ShowInputMessage;
                        if (dvs.PromptTitle != null) dvt.InputTitle = dvs.PromptTitle;
                        if (dvs.Prompt != null) dvt.InputMessage = dvs.Prompt;
                        if (dvs.ErrorTitle != null) dvt.ErrorTitle = dvs.ErrorTitle;
                        if (dvs.Error != null) dvt.ErrorMessage = dvs.Error;
                        if (dvs.ErrorStyle != null) dvt.ErrorStyle = dvs.ErrorStyle.Value.ToClosedXml();
                        if (dvs.Type != null) dvt.AllowedValues = dvs.Type.Value.ToClosedXml();
                        if (dvs.Operator != null) dvt.Operator = dvs.Operator.Value.ToClosedXml();
                        if (dvs.Formula1 != null) dvt.MinValue = dvs.Formula1.Text;
                        if (dvs.Formula2 != null) dvt.MaxValue = dvs.Formula2.Text;
                    }
                }
```

**Comment by Pankraty** [comment]
Fixed what you pointed and also found a bug I made.

File: ClosedXML_Tests/Excel/DataValidations/DataValidationTests.cs (hunk 4 above)
Comment (igitur) [reply ClosedXML_Tests/Excel/DataValidations/DataValidationTests.cs]: You still have to change the settings back? Or maybe test both?

Comment (Pankraty) [reply ClosedXML_Tests/Excel/DataValidations/DataValidationTests.cs]: Uh, sorry, missed there were multiple changes in this test.
