### PR TITLE
Correctly process transparent background (Fix #290)

### LINKED ISSUE #290: Copy BackgroundColor from one IXLCell to each IXLCell in an IXLRange
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**What is the current behavior?**
Unpredictable BackgroundColor value assignment. 

I try to use a default cell (A1) to have a Cell in the Default-Excel-Style, which I can then use to delete/reset Cells of different Ranges (A2:E2). (I haven't found another way to fully reset a cell, if there is, please tell me.) 

Not all Cells of Range (A2:E2) get the color of that origin Cell (A1), sometimes none (A2:E2 stay colored), sometimes only a few (only A2 gets the A1 Style, or A2 and B2 but not the rest, or A2 and C2 but not the rest, I have seen it all) and sometimes even the "origin Cell" gets the "destination Cell" BackgroundColor.  
Please have a look at code comments below.

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**
- I open a new Excel File, 
- select Range A2:E2, 
- hit the arrow Button next to the FillColor bucket in Excel,
- and choose a color of the shown "Designcolors"(<- german version)  palette 
- select another cell on the sheet
- Hit File -> save as "C:\MyTemp\empty.xlsx"
- Run Code in release or debug mode

**Did this work in previous versions of our tool?  Which versions?**
It worked for weeks with 
> cell.Value = "";
> cell.Style = DefaultCell.Style;
> cell.Style.Font.FontColor = XLColor.Black;
>   cell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.General;
now it wont. I don't know why, I havent changed the code or the file. (did a few runs with backup files with the same result)
In my production xlsx File (which I cannot provide) the origin Cell gets the color of a Range cell, and assigns that color to the whole Range too, I can't reproduce this behavior in my Testproject.

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[empty.xlsx](https://github.com/ClosedXML/ClosedXML/files/962121/empty.xlsx)

**Code to reproduce problem:**
```c#
static void Main(string[] args)
        {
            String Filename = @"C:\MyTemp\empty.xlsx";
            String Worksheet = "Tabelle1";
            using (XLWorkbook workbook = new XLWorkbook(Filename, XLEventTracking.Disabled))
            using (IXLWorksheet sheetXML = workbook.Worksheet(Worksheet))
            {
                IXLCell defaultcell = sheetXML.Cell(1, 1);
                IXLRange setColorRange = sheetXML.Range(2, 1, 2, 5);
                foreach (IXLCell cell in setColorRange.Cells())
                {
                    //cell.Style.Fill.SetBackgroundColor(defaultcell.Style.Fill.BackgroundColor); //leaves black background

                    //cell.Style = defaultcell.Style; 
                    //Works in this szenario, but not (anymore) in my "live.xlsx" which I cannot provide, sorry.
                    //the defaultcell AND all Range cells get the blue color

                    //cell.Style.Fill = defaultcell.Style.Fill; 
                    //Unpredictable behavior, most of the times A2 gets it right, rest of Range stays blue
                    //sometimes it manages to fill B2 and C2, sometimes only A2 and C2.... 
                    //I tried it with a new File each time and with the existing File. 

                    //cell.Style.Fill.BackgroundColor = defaultcell.Style.Fill.BackgroundColor; 
                    // right now it leaves a black background color, (tested with new file)
                    // usually I get the same result as I do with the cell.Style.Fill aproach (which makes sence)
                }
                workbook.Save(false);
            }
        }
```

package id="ClosedXML" version="0.87.1" targetFramework="net45"
package id="DocumentFormat.OpenXml" version="2.5" targetFramework="net45"
Microsoft Office Standard 2010 -> Excel: Version: 14.0.7173.5000 (32-Bit)
Visual Studio 2015 community Edition

Please let me know, if anything is unclear or more information is needed, thanks.

### PR DESCRIPTION
**Pull request by Pankraty**
This PR fixes #290 and #778.

In this PR I modified a logic of comparing the FillKeys so that two empty fills were considered the same no matter how their "emptiness" is specified - with PatternType.None, or with Indexed color 64, or with XLColor.NoColor.

After this was done I had to modify the logic for a simultaneous change of the `BackgroundColor` and `PatternType`. Without it, the cached "empty" fill was used even though the pattern type has changed to `Solid` (if the color remained Indexed(64) the fill still was empty) or the color changed to some non-transparent (the pattern remained `None` and fill was empty again).

To prevent the empty fills from saving to file the additional checks were added. Unlike some other entities (say, `patternFill`), for colors we should check `.HasAttributes` rather than `.HasChildren` - colors never have children.

Thanks to @igitur for the POC.

- [ ] C# Code Review: @csreviewer
- [ ] Test Automation Review: @csreviewer

### CODE REVIEW

File: ClosedXML/Excel/Style/Colors/XLColor_Static.cs [hunk 1]
```diff
@@ -169,9 +169,20 @@ public static XLColor FromTheme(XLThemeColor themeColor, Double themeTint)
             }
         }
 
-        private static XLColor noColor = new XLColor();
+        internal static bool IsNullOrTransparent(XLColor color)
```
Comment (igitur) [inline ClosedXML/Excel/Style/Colors/XLColor_Static.cs]: Isn't it better to have this a instance method on `XLColor` itself?

File: ClosedXML/Excel/Style/Colors/XLColor_Static.cs [hunk 2]
```diff
@@ -169,9 +169,20 @@ public static XLColor FromTheme(XLThemeColor themeColor, Double themeTint)
...
+        {
+            return color == null
+                || !color.HasValue
+                || IsTransparent(color.Key);
+        }
+
+        internal static bool IsTransparent(in XLColorKey colorKey)
```
Comment (igitur) [inline ClosedXML/Excel/Style/Colors/XLColor_Static.cs]: Same question for this one too.

File: ClosedXML/Excel/Style/Colors/XLColor_Static.cs (hunk 1 above)
Comment (Pankraty) [reply ClosedXML/Excel/Style/Colors/XLColor_Static.cs]: This would make the usage more complicated. Compare XLColor.IsNullOrTransparent(color) vs (color == null || color.IsTransparent()).

But maybe you're right.

Comment (igitur) [reply ClosedXML/Excel/Style/Colors/XLColor_Static.cs]: No, leave it like it is.

**Comment by igitur** [comment]
Commit f79a9080a691ab2bfacf46d1b9f648cad0cc0f53 broke the `LoadAndSaveTransparentBackgroundFill` test. Well, it made the test pass, but the reference file is now incorrect. If you open it, the cell of concern displays with a black background.
