### PR TITLE
Сonsolidation of conditional formats and data validation rules

### LINKED ISSUE #757: Conditional formatting consolidation break priority ordering
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.92.0

**What is the current behavior?**

The sequence of "conditional formatting rules" has been changed after export Excel by using ClosedXML in my program

**What is the expected behavior or new feature?**

The sequence should not be changed in Excel template after export excel.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
      using (XLWorkbook workbook = new XLWorkbook(@"FAI.xlsm"))
   {
       workbook.Save();
   }
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[test4.xlsx](https://github.com/ClosedXML/ClosedXML/files/1839700/test4.xlsx)

### PR DESCRIPTION
**Pull request by Pankraty**
This PR fixes #757.
There are many changes in this PR but that's because it is based on #709 and #758. After these two are merged I will rebase the current one. Meanwhile, it can be reviewed.

This PR consists of the following parts:
1. Implement a ```Consolidate``` method for ```XLRanges```. It rebuilds the ranges completely, combining everything that can be combined.
2. Define ```Ranges``` property for ```XLConditionalFormat``` that allows defining multiple ranges for a single conditional format without the need to split them. I am still not sure about what to do with the original ```Range``` property; for now, I marked it as an obsolete.
3. Re-implement a ```Consolidate``` method for ```XLConditionalFormats``` with respect to rules priorities. Similar rules are joined as long as this does not cause changing the order of rules affecting the same cells.
4. Implement a ```Consolidate``` method for ```XLDataValidations``` too. It is being called on a workbook saving and makes the rules definition much more compact in some cases.

- [ ] C# Code Review: @csreviewer
- [ ] Test Automation Review: @csreviewer

### CODE REVIEW

**Comment by igitur** [comment]
If you can rebase on `develop` that would be great, else merge and fix is fine.

**Comment by Pankraty** [comment]
Rebased

File: ClosedXML/Excel/ConditionalFormats/IXLConditionalFormat.cs [hunk 1]
```diff
@@ -140,8 +140,9 @@ public interface IXLConditionalFormat
         Boolean ShowIconOnly { get; }
         Boolean ShowBarOnly { get; }
         Boolean StopIfTrue { get; }
+        [Obsolete("Use Ranges instead")]
```
Comment (igitur) [inline ClosedXML/Excel/ConditionalFormats/IXLConditionalFormat.cs]: I actually think we should keep `Range` forever, not make it obsolete. Most/many conditional formats will refer to only 1 range and this property will ease it a lot.

File: ClosedXML/Excel/ConditionalFormats/Save/XLCFDatesOccuringConverter.cs [hunk 2]
```diff
@@ -29,7 +30,7 @@ public ConditionalFormattingRule Convert(IXLConditionalFormat cf, int priority,
 
             conditionalFormattingRule.TimePeriod = cf.TimePeriod.ToOpenXml();
 
-            var address = cf.Range.RangeAddress.FirstAddress.ToStringRelative(false);
+            var address = cf.Ranges.First().RangeAddress.FirstAddress.ToStringRelative(false);
```
Comment (igitur) [inline ClosedXML/Excel/ConditionalFormats/Save/XLCFDatesOccuringConverter.cs]: Just checking... shouldn't we use `cf.Range` instead of `cf.Ranges.First()` ?
So the question is, if there is more than one range, should this fail or continue?

Comment (Pankraty) [reply ClosedXML/Excel/ConditionalFormats/Save/XLCFDatesOccuringConverter.cs]: I just realized that here most likely we should use the top-left cell for all ranges, like [there](https://github.com/ClosedXML/ClosedXML/issues/757#issuecomment-380886527). I will check and if so will add ```BaseCellAddress``` property to XLConditionalFormat.

File: ClosedXML/Excel/ConditionalFormats/IXLConditionalFormat.cs (hunk 1 above)
Comment (Pankraty) [reply ClosedXML/Excel/ConditionalFormats/IXLConditionalFormat.cs]: OK

File: ClosedXML/Excel/ConditionalFormats/Save/XLCFDatesOccuringConverter.cs (hunk 2 above)
Comment (Pankraty) [reply ClosedXML/Excel/ConditionalFormats/Save/XLCFDatesOccuringConverter.cs]: > we should use the top-left cell for all ranges
No, it's OK to get the first cell of the first range.

> shouldn't we use ```cf.Range``` instead of ```cf.Ranges.First()```?
I made ```Range``` returning ```.FirstOrDefault``` instead of ```.Single()``` and reverted these changes. Rules with no ranges in collections are removed during consolidation, so we won't get NullRef here.
