### PR TITLE
Shift data validation ranges when inserting / delete ranges

### LINKED ISSUE #1046: Inserting an adjacent row does not copy the data validation of cells
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.94.999.1469

**What is the current behavior?**

Inserting an adjacent row does not copy the data validation of cells.

**What is the expected behavior or new feature?**

Inserting an adjacent row does copy the data validation. This would be similar to how ClosedXML copies other cell attributes (e.g. text wrapping), and would mimic the behavior of Excel.

**Did this work in previous versions of our tool?  Which versions?**

I do not know if this worked in previous versions.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

**Code to reproduce problem:**
```c#
public void Main()
{
    using (var workbook = new XLWorkbook())
    using (var worksheet = workbook.AddWorksheet("WorksheetOne"))
    {
        worksheet.Range("A1:A3")
            .SetValue(1);

        //This will copy to new row on insert
        worksheet
            .Cell("A1")
            .Style
            .Alignment
            .SetWrapText(true);

        //This will not copy to new row on insert
        worksheet
            .Cell("A1")
            .DataValidation
            .Decimal
            .Between(0,1);

        worksheet
            .Row(2)
            .InsertRowsAbove(1);

        worksheet
            .Cell("A2")
            .InsertCellsAbove(1);

        workbook.SaveAs("WorkbookOne.xlsx");
    }
}
```
- [X] I attached a sample spreadsheet.  (You can drag files on to this issue)
[WorkbookOne.xlsx](https://github.com/ClosedXML/ClosedXML/files/2516771/WorkbookOne.xlsx)

### PR DESCRIPTION
**Pull request by igitur**
Fixes #1046 
Closes #1042

### CODE REVIEW

File: ClosedXML/Excel/XLWorksheet.cs [hunk 1]
```diff
@@ -1173,6 +1174,52 @@ private void ShiftConditionalFormattingColumns(XLRange range, int columnsShifted
...
+                foreach (var dvRange in dvRanges)
+                {
+                    var dvAddress = dvRange.RangeAddress;
+                    IXLRange newRange;
+                    if (dvRange.Intersects(model))
+                    {
+                        newRange = Range(dvAddress.FirstAddress.RowNumber,
+                                         dvAddress.FirstAddress.ColumnNumber,
+                                         dvAddress.LastAddress.RowNumber,
+                                         dvAddress.LastAddress.ColumnNumber + columnsShifted);
```
Comment (Pankraty) [inline ClosedXML/Excel/XLWorksheet.cs]: There was an issue with the similar code (it was about a shifting of the conditional formats as I recall) when ranges became invalid after shifting if they included the last row or column. We should trim the result value by `XLHelper.MaxColumnNumber` (`MaxRowNumber` in the `ShiftDataValidationRows` method). An additional test case for this will also be useful.

Comment (igitur) [reply ClosedXML/Excel/XLWorksheet.cs]: Ah, you're referring to #1042?

Comment (Pankraty) [reply ClosedXML/Excel/XLWorksheet.cs]: Exactly
